# Test against these versions of Io.js and Node.js
environment:
  matrix:
  # node.js
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
  # io.js
    - nodejs_version: "1"
    - nodejs_version: "2"
    - nodejs_version: "3"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: if($env:nodejs_version -eq "0.8") {Install-Product node $env:nodejs_version}
  - ps: if($env:nodejs_version -ne "0.8") {Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)}
  # Install latest npm for 0.10 and 0.12
  - IF %nodejs_version% == 0.10 npm -g install npm
  - IF %nodejs_version% == 0.10 set PATH=%APPDATA%\npm;%PATH%
  - IF %nodejs_version% == 0.12 npm -g install npm
  - IF %nodejs_version% == 0.12 set PATH=%APPDATA%\npm;%PATH%
  # Install the module under test
  - npm install

# Post-install test scripts
test_script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - node_modules\.bin\mocha --reporter spec

# Don't actually build
build: off
